on: push

env:
  PYTHONPATH: .

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: pipx install poetry
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'poetry'

        - run: poetry install
        - run: poetry run mypy --explicit-package-bases steps
        - run: poetry run black --check .
        - run: poetry run pytest tests
